# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Reciplease_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reciplease_Project

  target 'Reciplease_ProjectTests' do
    inherit! :search_paths
	pod 'Alamofire', '~> 5.2'
    # Pods for testing
  end

end
